services:
    web:
        public: true
        container_name: qinglong
        image: whyour/qinglong:latest
        ports:
            - 5700:5700
        volumes: 
            - /ql/data
        resources:
          cpu: 1000m
          memory: 2050Mi
          storage:
            size: 5Gi
            class: standard
